### ISSUE TITLE
Mocking routes directly from file

### ISSUE THREAD

**Issue by doppiogancio** [Flagsmith/flagsmith-php-client#25]
I saw that in **ClientFixtures.php** file the routes are create using the "**withResponse**" method.

```
->withResponse(new Response(200, [], self::loadFileContents('flags.json')))
```

FYI you can also use the "**withFileResponse**" method like the following

```
->withFileResponse(self::DATA_DIR . 'flags.json')
```

**Comment by dabeeeenster** [comment]
Hi @doppiogancio - is this something you want to submit a PR for?

**Comment by doppiogancio** [comment]
Why not, with pleasure. If you add me to team I will be able to push a branch (or at least I think).

**Comment by dabeeeenster** [comment]
Can you fork the repo and submit a PR from there? Thanks!

**Comment by doppiogancio** [comment]
PR is ready
