### ISSUE TITLE
Possibility to implement PSRs? (Through Community submitted PR)

### ISSUE THREAD

**Issue by tm1000** [Flagsmith/flagsmith-php-client#4]
Hello!

Would you be willing to accept a PR that introduces  [PSR-18](https://www.php-fig.org/psr/psr-18/) and [PSR-17](https://www.php-fig.org/psr/psr-18/), for example Guzzle and [PSR-16](https://www.php-fig.org/psr/psr-16/) for example Symfony Cache to this library? This is how the unleashed client works (https://github.com/Unleash/unleash-client-php) and allows for more flexibility in the library. Additionally in terms of PSR-16 if one does not want to implement a cache they can just set the null driver so this library can actually work the same way as before it would just allow more flexibility than relying directly on CURL commands (like being able to async in PHP)

**Comment by dabeeeenster** [comment]
Hi @tm1000  - sure that would be extremely welcome! We're quite resource constrained at the moment but would be grateful for PRs from the community!

**Comment by tm1000** [comment]
@dabeeeenster thanks! I'll probably be working on this in the next few weeks and submit it here.
