### ISSUE TITLE
"flagsmith.Identity.something@email.com.xxxxxx" contains reserved characters "{}()/\@:"."

### ISSUE THREAD

**Issue by mariaresp** [Flagsmith/flagsmith-php-client#67]
Getting error "flagsmith.Identity.something@email.com.xxxxxx" contains reserved characters "{}()/\@:"." when using 
$flagsmith->withSkipCache(true)->getIdentityFlags($identity, $traits);

Identity we use is email address

**Comment by dabeeeenster** [comment]
Can you clarify where this error is coming from and how to reproduce it ideally with a code snippet?

**Comment by mariaresp** [comment]
Here is how we get identity flags

```public static function isFeatureEnabledByIdentity(string $flagName, string $identity) : bool
    {
        try {
            $flagsmith = self::initFlagsmith();
            $traits = (object) [ 'email' => $identity ];
            $flags = $flagsmith->withSkipCache(true)->getIdentityFlags($identity, $traits);

            return $flags->isFeatureEnabled($flagName);

        } catch (Throwable $e) {
            // Something went wrong - most probably the flag does not exists
            // Return false by default
            return false;
        }
    }

**Comment by mariaresp** [comment]
for initFlagsmith()
```private static function initFlagsmith() : Flagsmith
    {
        // Enable Smphony cache with file based driver, Save to EFS
        $symfonyCache = new FilesystemAdapter(
            'flagsmith', // Namespace
            self::CACHE_LIFE_TIME, // We set the Life time to 5 mins by defauly
            '/var/www/html/efs/cc/cache/'
        );

        $psr16Cache = new Psr16Cache($symfonyCache);

        return (new Flagsmith(
            GLOBAL_CONFIGS['FLAGSMITH_API_KEY'],
            GLOBAL_CONFIGS['FLAGSMITH_API_URL'],
            null, // Custom Headers
            self::CACHE_LIFE_TIME // Cache Lifetime in Seconds
        ))->withCache($psr16Cache);
    }

**Comment by dabeeeenster** [comment]
Can you try without the cache and see if the error persists?

**Comment by mariaresp** [comment]
yes it worked without cache

**Comment by dabeeeenster** [comment]
I think this must be related to the `FilesystemAdapter` ? What other adapters does `symfonyCache` offer that we could try and isolate this adapter?

**Comment by mariaresp** [comment]
Yes it is related to cache, but before the update to latest version v4.2.0 is it working fine, so our temporary solution is to downgrade to v4.1.2

Anything in your update that might be related to caching?

**Comment by gagantrivedi** [comment]
The issue caused by this line here: https://github.com/Flagsmith/flagsmith-php-client/compare/v4.1.2...v4.2.0#diff-2c2c9c12a5be0b654767fd59da8d95cb1a63b9b70d92bf7065f75b15d3844cbcR26 maybe we can use the hash of the identifier as the key instead of using the identifier

**Comment by dabeeeenster** [comment]
> The issue caused by this line here: https://github.com/Flagsmith/flagsmith-php-client/blob/main/src/Utils/IdentitiesGenerator.php#L26 maybe we can use the hash of the identifier as the key instead of using the identifier

Yep this sounds like a good solution

**Comment by gagantrivedi** [comment]
Hi @mariaresp  can you give 4.2.1 a try and let us know if that works?

**Comment by mariaresp** [comment]
Yes it worked. Thank you!
